version: '3.8'

services:
  mtg_db:
    container_name: mtg_db
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5431:5432
    volumes:
      - mtg_db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  mtg_db: {}
